services:
  - type: web
    name: jharkhand-tourism
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn core.wsgi:application"
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: jh-db
          property: connectionString

databases:
  - name: jh-db
    plan: free
